
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    directives_ordering: true
    always_declare_return_types: true
    avoid_shadowing_type_parameters: true
    unnecessary_this: true

analyzer:
  exclude: 
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  errors:
    invalid_annotation_target: ignore
