name: nacchofer31_portfolio
description: "My dev portfolio website. Built with flutter web."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.17
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/raw/
    - assets/images/
    - assets/images/skills/
    - assets/images/education/
    - assets/images/experience/
    - assets/images/projects/
    - assets/images/projects/druni/
    - assets/images/projects/dsbank/
    - assets/images/projects/gymloop/
    - assets/images/projects/imq/
    - assets/images/projects/visualsensor/
    - assets/images/projects/posterxxl/
    - assets/images/projects/skiana/
    - assets/images/projects/sportmaniacs/
    - assets/images/projects/randomboxd/
