name: Web Deployment

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    name: Build and Deploy Flutter Web
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --verbose

      - name: Copy Build Files to Docs
        run: |
          mkdir -p docs
          cp -avr build/web/* docs/
          cp docs/index.html docs/404.html

      - name: Commit and Push Changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
          message: "Deploy updated Flutter Web build 🚀"
